# Generated by go2rpm 1.9.0
%bcond_without check
%global debug_package %{nil}

# https://github.com/bgentry/go-netrc
%global goipath         github.com/bgentry/go-netrc
%global commit          9fd32a8b3d3d3f9d43c341bfe098430e07609480

%gometa -f

%global common_description %{expand:
Netrc file parser for Go programming language.}

%global golicenses      LICENSE
%global godocs          README.md examples

Name:           %{goname}
Version:        0
Release:        %autorelease -p
Summary:        Netrc file parser for Go programming language

License:        MIT
URL:            %{gourl}
Source:         %{gosource}

%description %{common_description}

%gopkg

%prep
%goprep
%autopatch -p1

%generate_buildrequires
%go_generate_buildrequires

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
%autochangelog
